### PR TITLE
Update for modern CipherSuites.

### PR DESCRIPTION
**Pull request by ouaibe**
Update GPG to configure s2k params.
Update nginx conf to specify more modern ciphersuites, ocsp stapling, https-enforcing CSP & xss protection flags.
Update postfix configuration to specify modern ciphersuites, ecdh support & random source.
Update sshd configuration to specify modern ciphersuites, kex, macs w/ etm, digests.
Create ssh client config matching the servers (host based).

This is a starting point for discussion, upon final agreement some comments at the beginning of the configuration files might have to be adjusted to reflect chosen ciphers.

### CODE REVIEW

**Comment by nemunaire** [comment]
Ciphers chosen for postfix are too strict, at least for Google:

```
[postfix/smtpd] connect from mail-yh0-f41.google.com[209.85.213.41]
[postfix/smtpd] SSL_accept error from mail-yh0-f41.google.com[209.85.213.41]: -1
[postfix/smtpd] warning: TLS library problem: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher:s3_srvr.c:1360:
[postfix/smtpd] lost connection after STARTTLS from mail-yh0-f41.google.com[209.85.213.41]
[postfix/smtpd] disconnect from mail-yh0-f41.google.com[209.85.213.41]
```

It seems their SMTP server sending mail doesn't support TLS v1.2.

I suggest adding `EECDH+aRSA+AES` to this cipherlist, which actually add `ECDHE-RSA-AES256-SHA` and `ECDHE-RSA-AES128-SHA`.

**Comment by ouaibe** [comment]
You're right, I had them in my own config locally but discarded anything SHA before making changes, it's a bit ironic that Google wouldn't support those but it serves as a great justification to put them back. 
I will change and push later.

**Comment by ecki** [comment]
I think the problem with SMTP STARTTLS is, that beeing too strict is actually harmfull as the fallback in that case is unencrypted. So one option I see here is to actually define 2 different cipher suites "modern" and "compat" and then you put all providers/peers where you know you can expect a good cipher into the modern and the other in the compat group. This is however highly MTA specific if this is possible. (It is easier for ssh).

**Comment by nemunaire** [comment]
Indeed, with the new cipherlist, I just have another `no shared cipher`:

```
[postfix/smtpd] connect from smtp22.services.sfr.fr[93.17.128.11]
[postfix/smtpd] SSL_accept error from smtp22.services.sfr.fr[93.17.128.11]: -1
[postfix/smtpd] warning: TLS library problem: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher:s3_srvr.c:1360:
[postfix/smtpd] lost connection after STARTTLS from smtp22.services.sfr.fr[93.17.128.11]
[postfix/smtpd] disconnect from smtp22.services.sfr.fr[93.17.128.11]
```

Remote server doesn't necessarily fallback to unencrypted stream: Google postpone the message delivery, but `sfr.fr` makes a new unencrypted connection.

**Comment by ouaibe** [comment]
I think using what Google uses as the minimal baseline could be somewhat acceptable, they are, at least putting some pressure for email encryption https://www.google.com/transparencyreport/saferemail/.
Another option to support more smtp servers would be to allow EDH in addition to EECDH, it's much slower, but not necessarily less secure (depending on param length) but for mail services it's not such a big deal, plus it's allowed in nginx config.

**Comment by prometheanfire** [comment]
ya, I've had a few servers that need EDH.

**Comment by nemunaire** [comment]
It seems that most of Microsoft's email servers require one of `AES256-SHA` or `AES128-SHA`, currently listed in `smtpd_tls_exclude_ciphers`.

With those ciphers excluded, the connection is lost:
```
[postfix/smtpd] connect from mail-am1lrp0010.outbound.protection.outlook.com[213.199.154.10]
[postfix/smtpd] SSL_accept error from mail-am1lrp0010.outbound.protection.outlook.com[213.199.154.10]: lost connection
[postfix/smtpd] lost connection after STARTTLS from mail-am1lrp0010.outbound.protection.outlook.com[213.199.154.10]
[postfix/smtpd] disconnect from mail-am1lrp0010.outbound.protection.outlook.com[213.199.154.10]
```

**Pull request closed without merging**
